# Generated by Django 4.2.24 on 2026-01-20 17:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineTelemetry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Timestamp when the telemetry data was recorded', verbose_name='Timestamp')),
                ('metric_type', models.CharField(choices=[('temperature', 'Temperature'), ('pressure', 'Pressure'), ('speed', 'Speed'), ('vibration', 'Vibration'), ('power', 'Power Consumption'), ('cycle_count', 'Cycle Count'), ('runtime', 'Runtime Hours'), ('error_count', 'Error Count'), ('throughput', 'Throughput'), ('efficiency', 'Efficiency'), ('humidity', 'Humidity'), ('force', 'Force'), ('position', 'Position'), ('flow_rate', 'Flow Rate'), ('custom', 'Custom Metric')], help_text='Type of metric being recorded', max_length=50, verbose_name='Metric Type')),
                ('metric_name', models.CharField(help_text='Specific name or identifier for the metric', max_length=100, verbose_name='Metric Name')),
                ('value', models.FloatField(help_text='Numeric value of the telemetry reading', validators=[django.core.validators.MinValueValidator(-1000000000000000.0), django.core.validators.MaxValueValidator(1000000000000000.0)], verbose_name='Value')),
                ('unit', models.CharField(blank=True, default='', help_text='Unit of measurement (e.g., celsius, psi, rpm)', max_length=50, verbose_name='Unit')),
                ('metadata', models.JSONField(blank=True, default=None, help_text='Additional metadata as JSON (e.g., sensor ID, location)', null=True, verbose_name='Metadata')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created in the database', verbose_name='Created')),
                ('machine_config', models.ForeignKey(help_text='The machine this telemetry data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='machine.machineconfig', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Machine Telemetry',
                'verbose_name_plural': 'Machine Telemetry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryThreshold',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('temperature', 'Temperature'), ('pressure', 'Pressure'), ('speed', 'Speed'), ('vibration', 'Vibration'), ('power', 'Power Consumption'), ('cycle_count', 'Cycle Count'), ('runtime', 'Runtime Hours'), ('error_count', 'Error Count'), ('throughput', 'Throughput'), ('efficiency', 'Efficiency'), ('humidity', 'Humidity'), ('force', 'Force'), ('position', 'Position'), ('flow_rate', 'Flow Rate'), ('custom', 'Custom Metric')], help_text='Type of metric this threshold applies to', max_length=50, verbose_name='Metric Type')),
                ('metric_name', models.CharField(blank=True, default='', help_text='Specific metric name (leave blank to apply to all metrics of this type)', max_length=100, verbose_name='Metric Name')),
                ('min_value', models.FloatField(blank=True, help_text='Minimum acceptable value (alerts generated if below)', null=True, verbose_name='Minimum Value')),
                ('max_value', models.FloatField(blank=True, help_text='Maximum acceptable value (alerts generated if above)', null=True, verbose_name='Maximum Value')),
                ('warning_min', models.FloatField(blank=True, help_text='Warning threshold for minimum value', null=True, verbose_name='Warning Minimum')),
                ('warning_max', models.FloatField(blank=True, help_text='Warning threshold for maximum value', null=True, verbose_name='Warning Maximum')),
                ('rate_of_change_threshold', models.FloatField(blank=True, help_text='Maximum acceptable rate of change per minute', null=True, verbose_name='Rate of Change Threshold')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this threshold is active', verbose_name='Enabled')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('machine_config', models.ForeignKey(help_text='The machine this threshold applies to', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_thresholds', to='machine.machineconfig', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Telemetry Threshold',
                'verbose_name_plural': 'Telemetry Thresholds',
                'unique_together': {('machine_config', 'metric_type', 'metric_name')},
            },
        ),
        migrations.CreateModel(
            name='TelemetryAlert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('threshold_high', 'High Threshold Exceeded'), ('threshold_low', 'Low Threshold Exceeded'), ('rate_of_change', 'Abnormal Rate of Change'), ('missing_data', 'Missing Data'), ('pattern_anomaly', 'Pattern Anomaly'), ('equipment_fault', 'Equipment Fault'), ('maintenance_due', 'Maintenance Due'), ('custom', 'Custom Alert')], help_text='Type of alert', max_length=50, verbose_name='Alert Type')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], default='warning', help_text='Severity level of the alert', max_length=20, verbose_name='Severity')),
                ('metric_type', models.CharField(blank=True, choices=[('temperature', 'Temperature'), ('pressure', 'Pressure'), ('speed', 'Speed'), ('vibration', 'Vibration'), ('power', 'Power Consumption'), ('cycle_count', 'Cycle Count'), ('runtime', 'Runtime Hours'), ('error_count', 'Error Count'), ('throughput', 'Throughput'), ('efficiency', 'Efficiency'), ('humidity', 'Humidity'), ('force', 'Force'), ('position', 'Position'), ('flow_rate', 'Flow Rate'), ('custom', 'Custom Metric')], default='', help_text='The metric type that triggered this alert', max_length=50, verbose_name='Metric Type')),
                ('metric_name', models.CharField(blank=True, default='', help_text='The specific metric that triggered this alert', max_length=100, verbose_name='Metric Name')),
                ('message', models.TextField(help_text='Detailed alert message', verbose_name='Message')),
                ('threshold_value', models.FloatField(blank=True, help_text='The threshold value that was exceeded', null=True, verbose_name='Threshold Value')),
                ('actual_value', models.FloatField(blank=True, help_text='The actual value that triggered the alert', null=True, verbose_name='Actual Value')),
                ('acknowledged', models.BooleanField(default=False, help_text='Whether this alert has been acknowledged', verbose_name='Acknowledged')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='Timestamp when the alert was acknowledged', null=True, verbose_name='Acknowledged At')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this alert was created', verbose_name='Created')),
                ('metadata', models.JSONField(blank=True, default=None, help_text='Additional metadata about the alert', null=True, verbose_name='Metadata')),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='User who acknowledged this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_telemetry_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Acknowledged By')),
                ('machine_config', models.ForeignKey(help_text='The machine this alert is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_alerts', to='machine.machineconfig', verbose_name='Machine')),
                ('telemetry_data', models.ForeignKey(blank=True, help_text='The telemetry data point that triggered this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='machine.machinetelemetry', verbose_name='Related Telemetry')),
            ],
            options={
                'verbose_name': 'Telemetry Alert',
                'verbose_name_plural': 'Telemetry Alerts',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['machine_config', 'created'], name='machine_tel_machine_f9603c_idx'), models.Index(fields=['severity', 'acknowledged'], name='machine_tel_severit_60240c_idx'), models.Index(fields=['created'], name='machine_tel_created_c5f9df_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='machinetelemetry',
            index=models.Index(fields=['machine_config', 'timestamp'], name='machine_mac_machine_983921_idx'),
        ),
        migrations.AddIndex(
            model_name='machinetelemetry',
            index=models.Index(fields=['machine_config', 'metric_type'], name='machine_mac_machine_436c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='machinetelemetry',
            index=models.Index(fields=['timestamp'], name='machine_mac_timesta_aa6264_idx'),
        ),
    ]
